---
title: "Tweets"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    self_contained: TRUE
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(DT)
```


```{r, echo=FALSE, out.width="100%", warning=FALSE}
# update archive with `get_tweets.R`

read_latest <- function(){
  fpath <- "../data/"
  if(!file.exists(fpath)){
    fpath <- "data"
  }
  
  archives <- list.files(fpath, pattern = "*likes.rds", 
                         full.names = TRUE, include.dirs = TRUE)
  dates <- sapply(archives, 
               function(x) strsplit(x, "_")[[1]][1])
  dates <- as.Date(
    sapply(dates, function(x) substring(x, nchar(x)-9, nchar(x))))
    
  dt <- readRDS(archives[which.max(dates)])
  dt <- data.frame(dt)
}

#####

dt <- read_latest()

dt$created_at <- strptime(as.POSIXct(dt$created_at), format = "%Y-%m-%d")

createLink <- function(x) {
  if(is.na(x)){
    return("")
  }else{
    sprintf(paste0('<a href="', URLdecode(x),'" target="_blank">', substr(x, 1, 25) ,'</a>'))
  }
}

dt$urls_expanded_url <- lapply(dt$urls_expanded_url, function(x) sapply(x, createLink))

other_url_rows <- unlist(lapply(dt$urls_expanded_url, function(x) { 
    length(x) < 1})) & 
      !is.na(dt$urls_expanded)

dt$urls_expanded_url[other_url_rows] <- 
  lapply(dt$urls_expanded[other_url_rows], 
         function(x) sapply(x[[1]], createLink))

dt$created_at <- format(dt$created_at, '%Y-%m-%d')

dt <- dplyr::select(dt, created_at, screen_name, text, urls_expanded_url)

dt_table <- DT::datatable(dt, 
                          options = list(# dom = 't',
                                         scrollX = TRUE,
                                         autoWidth = TRUE,
                  columnDefs = list(#list(width = '5%', targets = c(0,1,3)), 
                                    list(width = '70%', targets = c(2)))), 
                          rownames = FALSE,
                          fillContainer = TRUE,
                      width = "100%", 
                  colnames = c("Date", "Handle", "Text", "URL"))

dt_table <- formatStyle(dt_table, columns = 1:4, fontSize = '70%')
dt_table <- formatStyle(dt_table, columns = 3, width = '500px')


# dt_table <- formatDate(dt_table, columns = c(1), method = 'toLocaleDateString', 
#                       params = list(year = 'numeric', month = 'long', day = 'numeric'))

dt_table
# frameWidget(dt_table, width = "100%", height = 800, options = frameOptions(allowfullscreen = TRUE))

```
